Update OpenBCI Logo in the GUI
OpenBCI/OpenBCI_GUI pull request #1018
Opened 2021-12-07 21:10 UTC by retiutut

- [ ] Fixes #1010 

- [ ] Also found a null pointer error associated with Headplot and a threaded method "doHardCalcs".

- [ ] The rotating Cog gif needs to be looked at because it doesn't render entirely correct. Should be fixed or changed to something else before merging this PR.

2021-12-07 21:16 UTC, retiutut commented
![Screen Shot 2021-12-07 at 3 15 34 PM](https://user-images.githubusercontent.com/25914123/145107340-98853c15-14aa-42dd-af4f-982174098f4f.png
![Screen Shot 2021-12-07 at 3 15 56 PM](https://user-images.githubusercontent.com/25914123/145107381-addde712-f434-4665-b05a-1abf9e60df63.png)
)

2021-12-07 21:16 UTC, retiutut commented
![Screen Shot 2021-12-07 at 3 16 26 PM](https://user-images.githubusercontent.com/25914123/145107441-c001933f-1b73-4a12-9077-22a35f5d80d8.png
![Screen Shot 2021-12-07 at 3 16 45 PM](https://user-images.githubusercontent.com/25914123/145107486-f594fbea-711c-4015-a19f-474df488c145.png)
)

2021-12-08 14:56 UTC, Andrey1994 requested changes
changes about processing 4 should not be in PR about logo change

2021-12-08 14:57 UTC, Andrey1994 commented on OpenBCI_GUI/BoardBrainflow.pde
> +    protected double time_last_datapoint = -1.0;
and this too

2021-12-08 17:33 UTC, closed without merging