Ganglion Impedance Widget - Dec 2021 Update
OpenBCI/OpenBCI_GUI pull request #1022
Opened 2021-12-08 22:12 UTC by retiutut

Fixes #1021

2021-12-08 22:44 UTC, Andrey1994 approved these changes

2021-12-20 08:53 UTC, Andrey1994 requested changes

2021-12-20 08:53 UTC, Andrey1994 commented on OpenBCI_GUI/W_GanglionImpedance.pde
> -                        topNav.stopButtonWasPressed();
are you sure about this? there is a comment which explains why we stop it... at least lets remove this comment also
And I remember we had issues with impedance for ganglion, I am a little scared to touch this

2021-12-21 23:09 UTC, retiutut commented on OpenBCI_GUI/W_GanglionImpedance.pde
> -                        topNav.stopButtonWasPressed();
@Andrey1994 https://github.com/OpenBCI/OpenBCI_GUI/issues/1021

It does bad things for the App and PacketLossTracker.

2021-12-21 23:10 UTC, retiutut commented on OpenBCI_GUI/W_GanglionImpedance.pde
> -                        topNav.stopButtonWasPressed();
I can review this PR again before merging.

2022-02-02 02:13 UTC, retiutut commented
This PR addresses the issue and the GUI behaves properly.

2022-02-02 02:14 UTC, merged