Ganglion Native BLE
OpenBCI/OpenBCI_GUI pull request #1090
Opened 2022-12-07 17:45 UTC by retiutut

Fixes https://github.com/OpenBCI/OpenBCI_GUI/issues/1080

2022-12-08 18:17 UTC, Andrey1994 commented
In brainflow everything is done, and its in the process of porting to the gui...

2023-01-17 00:17 UTC, philippitts commented
In later versions of MacOS (generally MacOS 11+) there is an issue where Bluetooth permissions are not requested by the application. This prevents the embedded native BLE library from accessing the Bluetooth adapter and therefore Ganglion boards (and other Bluetooth devices) cannot be found.

This issue appears to be related to [application hardening requirements](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution) introduced in MacOS 10.14.5. Most importantly, the JDK 8 version that ships with Processing 3.5.4 and earlier [is not notarized](https://github.com/adoptium/temurin-build/issues/1130) and therefore cannot request permissions from the OS.

A workaround to the issue is updating the JDK in Processing to the latest version of JDK 8. This can be done with the following:

```
curl -O -L --insecure https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u352b08.tar.gz
tar -xf OpenJDK8U-jdk_x64_mac_hotspot_8u352b08.tar.gz
mv jdk8u352-b08 /Applications/Processing.app/Content/PlugIns/jdk1.8.0_202.jdk
```

Then follow the instructions for [running from the IDE](https://docs.openbci.com/Software/OpenBCISoftware/GUIDocs/#running-the-openbci-gui-from-the-processing-ide).

Note that applications exported from Processing 3.5.4 do not appear to ask for Bluetooth permissions even if the JDK is updated before exporting. Processing 3.5.4 is no longer maintained so downstream fixes may exist in Processing 4.

2023-01-22 20:58 UTC, philippitts requested changes

2023-01-22 20:58 UTC, philippitts commented on OpenBCI_GUI/ControlPanel.pde
> +                //controlPanel.bleBox.refreshGanglionBLEList();
Is this needed? Recommend uncommenting it if it's useful or removing it if it's not.

2023-01-22 20:58 UTC, philippitts commented on OpenBCI_GUI/OpenBCI_GUI.pde
> +    size(win_w, win_h);
Why the renderer change here? If this is a leftover from exploring Processing 4 upgrade paths, we should save it for a Processing 4 specific PR.

2023-01-23 23:11 UTC, retiutut commented on OpenBCI_GUI/OpenBCI_GUI.pde
> +    size(win_w, win_h);
Correct. Will do.

2023-01-23 23:13 UTC, retiutut commented on OpenBCI_GUI/ControlPanel.pde
> +                //controlPanel.bleBox.refreshGanglionBLEList();
I'll re-evaluate this line. Thanks. This PR needs a few more UX passes from myself, and I'll address these requested changes also.

2023-02-02 17:39 UTC, philippitts approved these changes

2023-02-02 17:41 UTC, retiutut commented
Wooo! Let's gooooo!

2023-02-02 17:42 UTC, merged