Refactor the creation and playback of OpenBCI GUI data files
OpenBCI/OpenBCI_GUI pull request #1120
Opened 2023-02-08 23:22 UTC by retiutut

- Fixes #1119 

- Also changes Default Railed percentages to 90% and 75%.

2023-02-08 23:49 UTC, retiutut commented
Still TODO:

- [ ] Create playback files using every board class
- [ ] Test playback files from every board class

2023-02-26 21:44 UTC, Andrey1994 reviewed
I dont get why synthetic board for brainflow is changed, it still has all these datatypes and maybe they can be useful for somebody

2023-02-26 21:44 UTC, Andrey1994 commented on OpenBCI_GUI/BoardBrainFlowSynthetic.pde
> +class BoardBrainFlowSynthetic extends BoardBrainFlow implements AccelerometerCapableBoard {
why did you remove other interfaces? Synthetic boards still supports them..

2023-02-27 15:59 UTC, retiutut commented on OpenBCI_GUI/BoardBrainFlowSynthetic.pde
> +class BoardBrainFlowSynthetic extends BoardBrainFlow implements AccelerometerCapableBoard {
I removed them because the widgets to visualize these data types do not exist in this copy of the GUI.

2023-03-02 08:29 UTC, Andrey1994 commented on OpenBCI_GUI/BoardBrainFlowSynthetic.pde
> +class BoardBrainFlowSynthetic extends BoardBrainFlow implements AccelerometerCapableBoard {
But now we have interfaces like EDACapableBoard which are not implemented by any class and not used at all. And they are not removed as a part of this PR... if you want to make it consistent probably we need to remove them but it may be more complicated to sync two forks in that case. So probably it makes sense to restore them in synthetic board

2023-03-14 17:17 UTC, retiutut commented on OpenBCI_GUI/BoardBrainFlowSynthetic.pde
> +class BoardBrainFlowSynthetic extends BoardBrainFlow implements AccelerometerCapableBoard {
Good catch. All that is left in this repo are these classes. I will remove them.

2023-05-05 18:42 UTC, retiutut commented on OpenBCI_GUI/DataWriterODF.pde
Fix line endings.

2023-05-05 18:44 UTC, retiutut commented on OpenBCI_GUI/FileBoard.pde
Fix line endings

2023-05-05 18:45 UTC, retiutut commented on OpenBCI_GUI/SignalCheckThresholds.pde
fix line endings

2023-05-05 18:45 UTC, retiutut commented on OpenBCI_GUI/W_Playback.pde
Fix line endings

2023-05-05 18:46 UTC, retiutut commented on OpenBCI_GUI/W_PulseSensor.pde
Fix line endings

2023-05-05 18:47 UTC, retiutut reviewed
Fix line endings in a few files.

2023-05-05 19:32 UTC, retiutut commented
Tested with:
- Cyton
- Cyton Daisy
- Cyton Daisy + Accelerometer
- Cyton Daisy + Analog Read
- Cyton Daisy + Digital Read (with pressing PROG)
- Ganglion Native Bluetooth
- Ganglion BLE112 Dongle
- Synthetic Board (yes this generates a file for testing and development reasons)
- Playback History Widget playing back all of the above use cases in rapid succession within one session

2023-05-05 20:07 UTC, retiutut commented
In W_Playback the MenuList object does not perform well upon resizing. This should be replaced by an array of buttons or some other solution. All other calls to this UI object are not resized, as they are in the Control Panel.

2023-05-05 20:10 UTC, retiutut commented
Sending to NYC office for final testing as performed here: https://github.com/OpenBCI/OpenBCI_GUI/pull/1120#issuecomment-1536686587

2023-05-09 20:29 UTC, isaacplotkin requested changes
Playback mode is working great on my end. I tested all the board configurations you mentioned. A few notes:
- The first time I click “Select OpenBCI playback file” after launching the GUI, the open file explorer window opens behind my other windows (Windows 10). Only happens the first time I click the button.
- Error when trying to record a 16 channel synthetic stream. Don’t get this problem when testing GUI 5.1.0
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/108891347/48db9f08-e15d-4268-9ffd-10500d06df26)
- Maybe add name of selected file below “Select OpenBCI playback file”. Not necessary but it confused me at first if I had selected a file

2023-05-09 21:43 UTC, retiutut commented
> Playback mode is working great on my end. I tested all the board configurations you mentioned. A few notes:
> 
> * The first time I click “Select OpenBCI playback file” after launching the GUI, the open file explorer window opens behind my other windows (Windows 10). Only happens the first time I click the button.
> * Error when trying to record a 16 channel synthetic stream. Don’t get this problem when testing GUI 5.1.0
>   ![image](https://user-images.githubusercontent.com/108891347/237212765-48db9f08-e15d-4268-9ffd-10500d06df26.png)
> * Maybe add name of selected file below “Select OpenBCI playback file”. Not necessary but it confused me at first if I had selected a file

Great catch! I'll fix this here in this PR. The session settings for both playback and synthetic sessions were misnamed.

We do say in the status bar at the bottom of the GUI that the file was either successful or failed to load the file. Also appears in the console log. We do this in the status bar since there is enough space to display longer file names.

![Screen Shot 2023-05-09 at 4 42 35 PM](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/c92a708f-77b5-4a2c-bbf3-a615abe906df)

2023-05-09 21:45 UTC, retiutut commented
Ok @isaacplotkin, the fix for synthetic mode not launching is in.

2023-05-15 17:55 UTC, isaacplotkin approved these changes

2023-05-15 18:34 UTC, merged