Update to Processing 4.2
OpenBCI/OpenBCI_GUI pull request #1166
Opened 2023-07-12 20:16 UTC by retiutut

**Modify App to be fully compatible with Processing 4**

Closes #1111 

There are still issues with child windows not being able to be resized and closed properly. To help us move forward for now, FilterUI, ConsoleLog, and EMG Settings UI have been made non-resizeable. A boolean has been left in FilterUI that would allow this again and easy testing, should a fix become available.

___

**CI/CD Update**

Closes #1170 
Closes #1162 
Closes #1171

2023-07-12 20:57 UTC, Rexblk81 approved these changes

2023-07-31 17:57 UTC, philippitts requested changes
- [x] Recommend removing the debug lines that show up in the console log whenever the window is moved.
- [x] There is no window resizing cursor on Windows. Can this be added?

2023-07-31 17:57 UTC, philippitts commented on release_script/mac_only/Certificates_2023.p12.enc
Can this be made into a build variable so it's not exposed as a file?

2023-07-31 17:57 UTC, philippitts commented on release_script/mac_only/dmgbuild_settings_old.py
Unless this is actively used now, it should be removed. The git history will keep track of old files.

2023-07-31 17:58 UTC, retiutut commented on release_script/mac_only/Certificates_2023.p12.enc
It cannot.

2023-07-31 17:59 UTC, philippitts commented on release_script/mac_only/Certificates_2023.p12.enc
https://stackoverflow.com/questions/70791640/how-to-set-gihub-secret-with-a-binary-file-for-github-workflow

2023-07-31 17:59 UTC, retiutut commented
> [ ] Recommend removing the debug lines that show up in the console log whenever the window is moved.

Steps to replicate?

2023-07-31 17:59 UTC, philippitts commented on release_script/mac_only/Certificates_2023.p12.enc
https://docs.github.com/en/actions/security-guides/encrypted-secrets#storing-base64-binary-blobs-as-secrets

2023-07-31 18:01 UTC, retiutut commented on release_script/mac_only/Certificates_2023.p12.enc
This changes the process for CI/CD a good bit I think.

2023-07-31 18:02 UTC, philippitts commented
> > [ ] Recommend removing the debug lines that show up in the console log whenever the window is moved.
> 
> Steps to replicate?

Launch from Processing 4 and then move the GUI window around. You should see something like this:

```
__MOVE__ 589 760
__MOVE__ 589 761
__MOVE__ 588 761
__MOVE__ 588 762
__MOVE__ 588 763
__MOVE__ 588 764
__MOVE__ 587 765
__MOVE__ 587 766
__MOVE__ 587 767
__MOVE__ 587 768
__MOVE__ 587 769
__MOVE__ 586 769
```

2023-07-31 18:27 UTC, retiutut commented
> > > [ ] Recommend removing the debug lines that show up in the console log whenever the window is moved.
> > 
> > 
> > Steps to replicate?
> 
> Launch from Processing 4 and then move the GUI window around. You should see something like this:
> 
> ```
> __MOVE__ 589 760
> __MOVE__ 589 761
> __MOVE__ 588 761
> __MOVE__ 588 762
> __MOVE__ 588 763
> __MOVE__ 588 764
> __MOVE__ 587 765
> __MOVE__ 587 766
> __MOVE__ 587 767
> __MOVE__ 587 768
> __MOVE__ 587 769
> __MOVE__ 586 769
> ```

This is something added by Processing 4. Only shows when running from the Processing 4 IDE.

>There is no window resizing cursor on Windows. Can this be added?

We can resize windows from the top left.

2023-07-31 19:33 UTC, retiutut commented on release_script/mac_only/Certificates_2023.p12.enc
Ok will do!

2023-08-01 21:16 UTC, philippitts approved these changes

2023-08-01 21:19 UTC, merged