Add Software Marker Widget
OpenBCI/OpenBCI_GUI pull request #1174
Opened 2023-08-02 21:47 UTC by retiutut

Closes #1091

2023-08-03 20:46 UTC, retiutut commented
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/5064137b-4e77-4b54-a622-3e55432bd7f7)

Markers making their way into OpenBCI CSV files. Loaded into spreadsheet and sorted that column. You can see the markers next to the timestamp channel.

2023-08-03 21:10 UTC, retiutut commented
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/971a284f-7ba3-4abb-8417-d6cb3e940c5b)


We will print an approximate time that a marker was inserted into the data. Here we see that the timestamp was correct down to the millisecond!

2023-08-04 20:03 UTC, retiutut commented
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/2ada22f6-74d2-4a21-8498-e87f76e63f85)

Markers showing up in playback!

2023-08-04 22:35 UTC, retiutut commented
LSL Networking Test
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/a5be6eba-995d-4b7d-875c-254c6900e4cb)

UDP Networking Test (everything is right but the sampling rate calculation is incorrect)
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/39b55e40-5db7-4b04-8201-bdc7c5463c98)

OSC Networking Test
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/d85f365a-dee8-4915-8709-5dfce85c235b)

2023-08-10 17:11 UTC, philippitts requested changes
- [ ] Add some padding on the right side of the buttons
- [ ] Consider making the buttons larger and splitting them into two rows
- [ ] Autoscale the height of the graph

2023-08-10 19:36 UTC, retiutut commented
> * [ ]  Add some padding on the right side of the buttons
> * [x]  Consider making the buttons larger and splitting them into two rows
> * [ ]  Autoscale the height of the graph

I don't think autoscaling is the way to go here (for now), until users are allowed to stream in floats from another program. Then, it should be the only option for that source.

2023-08-14 21:58 UTC, retiutut commented
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/0ded7e5f-3f1c-47d6-9436-b01b6bb0e4e7)
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/d9529870-a5c7-4633-bc29-177f81da4d24)


Successfully inserting markers (as floats) from external process over UDP.

2023-08-15 19:00 UTC, retiutut commented
![image](https://github.com/OpenBCI/OpenBCI_GUI/assets/25914123/43e50232-980f-47e8-8992-6b4cc0c627ef)

2023-08-16 16:51 UTC, philippitts requested changes
- [ ] It looks like there a few files where the whole file ended up as a diff for some reason. Can you double check your line endings and try restaging the files?
- [ ] I'm not sure how to provide external triggers via something like [netcat](https://netcat.sourceforge.net/). Can you provide some information (PR comment is fine) on this? Should the external process listen or host the connection? Does the stream have to be started first?

2023-08-16 16:51 UTC, philippitts commented on Networking-Test-Kit/UDP/udp_receive_marker.py
It looks like there is some commented out code that can be removed here.

2023-08-16 16:51 UTC, philippitts commented on Networking-Test-Kit/UDP/udp_send_marker.py
> +    args = parser.parse_args()
These arguments talk about an OSC server, but this is a UDP utility. I think this should be updated to UDP. It would also make sense to capitalize IP in this help stream.

2023-08-16 16:51 UTC, philippitts commented on OpenBCI_GUI/Board.pde
What is actually changed here? Looks like line endings or something caused the whole file to be a diff.

2023-08-16 16:51 UTC, philippitts commented on OpenBCI_GUI/W_CytonImpedance.pde
What actually changed here? Looks like the whole file is a diff.

2023-08-16 16:52 UTC, philippitts commented
> > * [ ]   Add some padding on the right side of the buttons
> > * [x]   Consider making the buttons larger and splitting them into two rows
> > * [ ]   Autoscale the height of the graph
> 
> I don't think autoscaling is the way to go here (for now), until users are allowed to stream in floats from another program. Then, it should be the only option for that source.

Maybe we should add it now that it's possible to stream in floats from an external source?

2023-08-16 17:34 UTC, retiutut commented
> > > * [ ]    Add some padding on the right side of the buttons
> > > * [x]    Consider making the buttons larger and splitting them into two rows
> > > * [ ]    Autoscale the height of the graph
> > 
> > 
> > I don't think autoscaling is the way to go here (for now), until users are allowed to stream in floats from another program. Then, it should be the only option for that source.
> 
> Maybe we should add it now that it's possible to stream in floats from an external source?

Instead of this, users now have full control over the Y Axis, up to 20.0. Autoscale is kind of weird here since all values should be greater than 0, and it may cause "bouncing" when the graph resizes. Overall, the UX is likely better without the Y axis dynamically changing.

2023-08-16 18:39 UTC, retiutut commented on Networking-Test-Kit/UDP/udp_receive_marker.py
Sure, these kinds of scripts usually get changed when debugging. Leaving just 1-2 lines in that help with that.

2023-08-16 18:41 UTC, retiutut commented on Networking-Test-Kit/UDP/udp_send_marker.py
> +    args = parser.parse_args()
I agree. Thanks for helping clean this up since it's a new file.

2023-08-21 15:59 UTC, retiutut commented
> * [x]  It looks like there a few files where the whole file ended up as a diff for some reason. Can you double check your line endings and try restaging the files?
> * [ ]  I'm not sure how to provide external triggers via something like [netcat](https://netcat.sourceforge.net/). Can you provide some information (PR comment is fine) on this? Should the external process listen or host the connection? Does the stream have to be started first?

In the included Python example in `NetworkingTestScripts` folder, we send a single `float` over UDP to the specified IP and Port. Though, **the float is packed as a byte array**.

2023-08-28 01:21 UTC, merged