Process widget data in background when widgets are closed
OpenBCI/OpenBCI_GUI pull request #1181
Opened 2023-08-28 21:17 UTC by retiutut

Networking Outputs, and those that need data processed in the background:

- [ ] - Time Series filtered - Done
- [ ] - Time Series unfiltered - Done
- [ ] - **Focus - NEED**
- [ ] - FFT - Done
- [ ] - EMG - Done
- [ ] - **AvgBandPower - NEED**
- [ ] - **BandPower - NEED**
- [ ] - **Accel/Aux - NEED**
- [ ] - **Pulse - NEED**
- [ ] - **EMG Joystick - NEED**
- [ ] - Marker - Done

2023-09-06 22:52 UTC, philippitts requested changes

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +    }
Optional - you might consider extracting the LSL and non-LSL logic into separate methods.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        }
Optional - a switch statement may be more clear here, offer better logical flow, and reduce the number of comparisons required. The number of comparisons matters since this code runs in an update loop.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        */
Optional - it might make sense to extract this to a separate method and then have a single call to that method commented out here.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        final int IS_METRIC = w_focus.getMetricExceedsThreshold();
Action - this name is confusing. MetricValue or similar would be better. I recommend not prefixing with 'Is' since it's not a boolean. The name should also be more about the value than the fact it is a metric (it's always a metric regardless if it's currently exceeding the threshold).

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +    }
Optional - For all of these send methods, it would read more clearly if the individual network type sections had their own send methods. For example:

```
private void sendFFTData() {
    if (this.protocol.equals("OSC")) sendFFTDataOSC();
    else if (this.protocol.equals("UDP")) sendFFTDataUDP();
    else if (this.protocol.equals("LSL")) sendFFTDataLSL();
    else if (this.protocol.equals("Serial")) sendFFTDataSerial();
}
```

You could even do the protocol string comparison in `sendData` and then pass it down as an enum to speed things up. I wouldn't recommend using a switch statement here because it would decrease the readability for some minor speed increases, but I could see it either way.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        */
Even better - use a global static final `DEBUG` variable or similar and execute the method if it is set.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        */
There are several other commented out blocks that would benefit in the same way.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        */
Even better - create a logger class and log information there at different severity levels. This will allow you to print, save, or send the debug output however you like and give you one section of code to manage logging.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +                    msg.add(dataProcessing.avgPowerInBins[i][j]); // [CHAN][BAND]
Action - Why not just name them channel and band?

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +            // }
Action - This code should be removed or the exception should be implemented.

2023-09-06 22:52 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +            // Open Serial Port! %%%%%
Info - what does `%%%%` mean?

2023-09-07 17:28 UTC, philippitts commented
Tested and confirmed the changes are working as expected 👍

2023-09-07 17:45 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        final int IS_METRIC = w_focus.getMetricExceedsThreshold();
It actually is a boolean, though represented as a 0 or 1.

2023-09-07 17:57 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        final int IS_METRIC = w_focus.getMetricExceedsThreshold();
Changing to `metricValue`. This should not have been IS_METRIC since it's a local final variable. I also agree with word choice as you have said.

2023-09-07 18:00 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +                    msg.add(dataProcessing.avgPowerInBins[i][j]); // [CHAN][BAND]
Agreed.

2023-09-07 18:05 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +            // }
Yes.

2023-09-07 18:05 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +            // Open Serial Port! %%%%%
I have no clue.

2023-09-07 18:08 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +    }
Though I don't like all of the `if` statements in this class, keeping the sendDatatypeData() method together does help with development when comparing how data is sent over multiple protocols.

2023-09-11 18:53 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +        */
Putting this as it's own method since it's reused and hiding behind a debug flag.

2023-09-11 19:47 UTC, philippitts approved these changes
I recommend checking the debug flag before entering the debug method, rather than after. The function name should be something of a contract to the developer. If it says it will do something, it should do it. In this case, the function name is `debugTimeSeriesDataSamplingRate` but in truth it's more like `debugTimeSeriesDataSamplingRateIfDebugFlagIsSet` as implemented. That could be confusing to a future developer who calls that function, but doesn't set the flag. Setting the flag outside the function avoids that confusion.

Everything else looks good - no need to re-request a review after fixing the above. I'll approve now and you can go ahead and merge after.

2023-09-11 19:47 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +
Action - It would be better to check the `debugSamplingRate` flag here rather than in the method. The method shouldn't be called if the flag isn't set.

2023-09-11 19:47 UTC, philippitts commented on OpenBCI_GUI/NetworkStreamOut.pde
> +
Action - same as above. Check the debug flag here rather than in the function. If the function is called, the debugging should be done.

2023-09-11 20:38 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +
Will do.

2023-09-11 20:38 UTC, retiutut commented on OpenBCI_GUI/NetworkStreamOut.pde
> +
Done.

2023-09-11 20:53 UTC, merged

2023-09-11 20:55 UTC, retiutut commented
Closes #1094