Add EV certificate signing for Windows builds
OpenBCI/OpenBCI_GUI pull request #1186
Opened 2023-09-12 19:35 UTC by philippitts

- Replaces code signing for Windows builds with Extended Validation code signing which provides additional guarantees to end-user systems and reduces warning about untrusted software
- Extracts code signing along with other OS specific logic from the `make_release.py` script
- Decomposes the `make_release.py` script into a `build.py` and `package.py` script

2023-09-12 21:00 UTC, retiutut commented
Looking great so far. Did an early review.

2023-09-12 22:57 UTC, philippitts commented
@retiutut can you double check that the BrainFlow library setup for MacOS is still correct? I ran builds on Windows and MacOS and they seem correct, but it would be great to have you confirm it.

2023-09-12 23:00 UTC, philippitts commented
The v5 GUI used to store build artifacts with timestamps in the names, but we've taken those out for v6. If you prefer to have timestamps in the name we can just drop the related commit and it should work. However, I think we can use versioning for the artifacts in AWS and it will work better.

2023-09-13 17:25 UTC, retiutut requested changes

2023-09-13 17:25 UTC, retiutut commented on release/package.py
> +    else:
It's not explicit here that this is the case for Windows. Can we make it more obvious?

2023-09-13 17:40 UTC, retiutut requested changes

2023-09-13 23:04 UTC, philippitts commented
Updated the PR based on your feedback and tested on Windows, MacOS, and Linux. Things are working as expected and it's ready for another review pass.

2023-09-14 16:52 UTC, merged