Fixed Broken URL for Ganglion and formatted the readme page
OpenBCI/OpenBCI_GUI pull request #1218
Opened 2024-09-12 17:41 UTC by sigdelsanjog

2024-09-16 19:40 UTC, WilczynskiT approved these changes
Looks good, the links are correct now

2024-09-16 19:42 UTC, WilczynskiT requested changes
But please merge into development instead of master:
![image](https://github.com/user-attachments/assets/fadb4363-fb38-4ca9-aca9-27186b487a5e)

2024-10-25 03:23 UTC, sigdelsanjog commented
Updated the base to development.

2024-10-25 03:24 UTC, sigdelsanjog commented
@retiutut

2024-12-27 19:34 UTC, sigdelsanjog commented
@WilczynskiT

2025-01-29 00:53 UTC, WilczynskiT approved these changes

2025-01-29 15:56 UTC, retiutut approved these changes

2025-01-29 15:57 UTC, merged