downsample ppg
OpenBCI/OpenBCI_GUI pull request #875
Opened 2020-09-09 21:20 UTC by Andrey1994

Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

2020-09-09 21:38 UTC, retiutut commented on OpenBCI_GUI/W_NovaAux.pde
>          for (int i=0; i < nPoints; i++) {
Maybe these two `for` loops can be refactored to just one?

2020-09-09 21:42 UTC, retiutut requested changes

2020-09-09 21:42 UTC, retiutut commented on OpenBCI_GUI/BoardNovaXR.pde
> +final boolean novaXREnabled = true;
This needs to be set back to `false` before merging

2020-09-10 00:00 UTC, retiutut commented
Waiting for results from internal test on this fix...

2020-09-11 14:26 UTC, Andrey1994 commented
tested with real device and looks fine

2020-09-11 14:27 UTC, merged